#!/usr/bin/env python3
"""
Extract per-page inline critical CSS from HTTrack mirror and save to public/css/pages/.
These style blocks (id="et-critical-inline-css", "divi-style-inline-inline-css", etc.)
are generated by Divi/WP per page and are critical for correct rendering.
"""

import os
import re

MIRROR = '/Users/macbookpro14m1pro/Desktop/spartanaccounts/FBRsoftware.com'
OUT_DIR = '/Users/macbookpro14m1pro/Desktop/splendid-astro/public/css/pages'

# Map: astro page slug -> path relative to mirror root
PAGES = {
    '__home__': 'index.html',
    'accounting': 'accounting/index.html',
    'become-our-partner': 'become-our-partner/index.html',
    'book-stores-software': 'book-stores-software/index.html',
    'computer-accessories-software': 'computer-accessories-software/index.html',
    'contact': 'contact/index.html',
    'customer-portal-app': 'customer-portal-app/index.html',
    'distribution-wholesale-software': 'distribution-wholesale-software/index.html',
    'ecommerce-accounting': 'ecommerce-accounting/index.html',
    'electronics-appliances-software': 'electronics-appliances-software/index.html',
    'fbr-digital-invoicing-software': 'fbr-digital-invoicing-software/index.html',
    'free-trial': 'free-trial/index.html',
    'garment-shop-software': 'garment-shop-software/index.html',
    'inventory': 'inventory/index.html',
    'inventory-management-system': 'inventory-management-system/index.html',
    'manufacturing': 'manufacturing/index.html',
    'online-crm-system': 'online-crm-system/index.html',
    'online-pos-fbr-integration': 'online-pos-fbr-integration/index.html',
    'order-booking-app': 'order-booking-app/index.html',
    'point-of-sale': 'point-of-sale/index.html',
    'pricing-plan': 'pricing-plan/index.html',
    'privacy-policy': 'privacy-policy/index.html',
    'purchases': 'purchases/index.html',
    'reporting': 'reporting/index.html',
    'restaurant-software': 'restaurant-software/index.html',
    'restaurants-bakers-software': 'restaurants-bakers-software/index.html',
    'retail-stores-software': 'retail-stores-software/index.html',
    'sales': 'sales/index.html',
    'sales-tracking-app': 'sales-tracking-app/index.html',
    'shoe-stores-software': 'shoe-stores-software/index.html',
    'splendid-invoices-app': 'splendid-invoices-app/index.html',
    'terms-and-conditions': 'terms-and-conditions/index.html',
    'user-data-deletion-request': 'user-data-deletion-request/index.html',
    'video': 'video/index.html',
}

# Style block IDs to extract (in order of importance)
STYLE_IDS = [
    'et-critical-inline-css',
    'divi-style-inline-inline-css',
    'divi-dynamic-critical-inline-css',
    'minerva-kb/css-inline-css',
    'global-styles-inline-css',
]

def extract_inline_styles(html):
    """Extract content of named <style> blocks."""
    collected = []
    for sid in STYLE_IDS:
        # Match <style ...id="sid"...>...</style>
        pattern = r'<style[^>]*id=["\']' + re.escape(sid) + r'["\'][^>]*>(.*?)</style>'
        m = re.search(pattern, html, re.DOTALL | re.IGNORECASE)
        if m:
            content = m.group(1).strip()
            if content:
                collected.append(f'/* {sid} */\n{content}')
    return '\n\n'.join(collected)

os.makedirs(OUT_DIR, exist_ok=True)

for slug, rel_path in PAGES.items():
    src = os.path.join(MIRROR, rel_path)
    if not os.path.exists(src):
        print(f'MISSING: {src}')
        continue
    with open(src, 'r', encoding='utf-8', errors='replace') as f:
        html = f.read()
    css = extract_inline_styles(html)
    if css:
        out_file = os.path.join(OUT_DIR, f'{slug}.css')
        with open(out_file, 'w', encoding='utf-8') as f:
            f.write(css + '\n')
        size = len(css)
        print(f'OK  {slug:40s} {size:7d} bytes')
    else:
        print(f'NO CSS: {slug}')
